name: Continuous Integration

on:
  pull_request:
  push:
    branches: master

jobs:
  python-tests:
    name: Python tests
    runs-on: ubuntu-20.04
    strategy:
        matrix:
            python: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install full dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ffmpeg \
            gir1.2-gtk-3.0 \
            libasound2-dev \
            libdbus-1-dev \
            libfftw3-dev \
            libgirepository1.0-dev \
            libmpv-dev \
            libnss3 \
            libpango1.0-dev \
            libpulse-dev \
            libqt5gui5 \
            pulseaudio \
            xvfb \
            zip
      - name: Intall python package
        run: pip install . --verbose
      - name: Run Tests
        run: ./dev/test-qt-bindings.sh

  python-linter:
      name: Python linter
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install linter
          run: python -m pip install flake8
        - name: Run linter
          run: python -m flake8 .

  python-fmt:
      name: Python formatting
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install formatting tools
          run: python -m pip install black isort
        - name: Run black
          run: python -m black . --check
        - name: Run isort
          run: python -m isort . --check
