name: Continuous Integration

on:
  pull_request:
  push:
    branches: master

jobs:
  python-tests:
    name: Python tests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              ffmpeg \
              gir1.2-gtk-3.0 \
              libfftw3-dev \
              libgirepository1.0-dev \
              libmpv-dev \
              libnss3 \
              libpulse-dev \
              libqt5gui5 \
              pulseaudio \
              xvfb \
              vlc \
              mpv
          python -m pip install -r dev/build_requires.txt
      - name: Run Tests
        run: sh dev/run-tests-docker.sh

  python-linter:
      name: Python linter
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install Linter
          run: python3 -m pip install flake8
        - name: Run Linter
          run: python3 -m flake8 . --ignore='F821,W503,E731'
