name: Continuous Integration

on:
  pull_request:
  push:
    branches: master

jobs:
  rust-check:
    name: Rust check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install core dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libasound2-dev \
            libdbus-1-dev \
            libmpv-dev \
            libpulse-dev \
            pulseaudio
      - uses: actions-rs/cargo@v1
        with:
          command: check

  rust-test:
    name: Rust test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install core dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libasound2-dev \
            libdbus-1-dev \
            libmpv-dev \
            libpulse-dev \
            pulseaudio
      # FIXME: Workaround until https://github.com/PyO3/pyo3/issues/341 is
      # fixed.
      - run: cd src/core
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
      - run: cd ../audiosync
      - uses: actions-rs/cargo@v1
        with:
          command: test

  rust-fmt:
    name: Rust formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  rust-clippy:
    name: Rust clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install core dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libasound2-dev \
            libdbus-1-dev \
            libmpv-dev \
            libpulse-dev \
            pulseaudio
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
    
  python-tests:
    name: Python tests
    runs-on: ubuntu-20.04
    strategy:
        matrix:
            python: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install full dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ffmpeg \
            gir1.2-gtk-3.0 \
            libasound2-dev \
            libdbus-1-dev \
            libfftw3-dev \
            libgirepository1.0-dev \
            libmpv-dev \
            libnss3 \
            libpango1.0-dev \
            libpulse-dev \
            pulseaudio \
            xvfb \
            zip
      - name: Intall python package
        run: pip install . --verbose
      - name: Run Tests
        run: sh dev/run-python-tests.sh

  python-linter:
      name: Python linter
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install linter
          run: python -m pip install flake8
        - name: Run linter
          run: python -m flake8 .

  python-fmt:
      name: Python formatting
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install formatting tools
          run: python -m pip install black isort
        - name: Run black
          run: python -m black . --check
        - name: Run isort
          run: python -m isort . --check
