name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
      name: Upload Assets
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04, windows-latest]
          include:
            - os: ubuntu-20.04
            - os: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Get the tag name
          id: tag-name
          uses: olegtarasov/get-tag@v2

        - name: Setup on Windows
          if: matrix.os == 'windows-latest'
          shell: pwsh
          run: |
            choco install wget 7zip.install
            pip install .[dev] --verbose
            ./build.py

        - name: Setup on Linux
          if: matrix.os == 'ubuntu-20.04'
          run: |
            sudo apt-get update -y
            sudo apt-get install curl -y
            curl -fsSL https://get.docker.com | sudo sh
            sudo docker build -t vidify .
            sudo docker run -v $PWD:/vidify -t vidify ./build.py

        - name: Uploading Release Assets
          uses: softprops/action-gh-release@v1
          with:
            body: ""
            files: ./build/vidify-*.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Uploading to PyPi
          if: matrix.os == 'ubuntu-20.04'
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            sudo --preserve-env docker run \
                --env TWINE_USERNAME --env TWINE_PASSWORD \
                vidify /bin/sh -c \
                    'pip install twine; \
                    python setup.py sdist bdist_wheel; \
                    twine upload dist/*'
